# 1D array without numpy

In [5]:
import random

# Create a 1D array with random numbers
n = 20  
array_1d = [random.randint(1, 100) for _ in range(n)]
print(array_1d)


[15, 30, 66, 70, 21, 61, 45, 55, 52, 77, 76, 57, 98, 90, 22, 17, 64, 26, 5, 97]


# 1D array with numpy

In [6]:
import numpy as np

# Create a 1D NumPy array with random numbers
n = 20  
array_1d = np.random.randint(1, 100, n)
print(array_1d)


[84 24 99 91 27 61  4 32 39 86 30 94 51 88 90 24 11 32 26 97]


# 2D array without numpy

In [7]:
import random

# Define the dimensions of the 2D array
rows = 5
cols = 5

# Create a 2D array with random numbers
array_2d = [[random.randint(1, 100) for _ in range(cols)] for _ in range(rows)]
for row in array_2d:
    print(row)


[64, 81, 57, 39, 22]
[74, 19, 40, 52, 76]
[63, 70, 71, 3, 73]
[56, 28, 5, 19, 29]
[53, 29, 20, 87, 73]


# 2D array with numpy

In [8]:
import numpy as np

# Define the dimensions of the 2D array
rows = 4
cols = 5

# Create a 2D NumPy array with random numbers
array_2d = np.random.randint(1, 100, size=(rows, cols))
print(array_2d)

[[36 49 34 25 10]
 [37 96 91 22 89]
 [96 69 65 66 85]
 [ 8 69 38 27 42]]


# Functions related to array computation using numpy

In [9]:
import numpy as np

# Create two example arrays
array1 = np.array([10, 20, 30, 40, 50])
array2 = np.array([50, 40, 30, 20, 10])

# Display the original arrays
print("Original Array 1:", array1)
print("Original Array 2:", array2)

Original Array 1: [10 20 30 40 50]
Original Array 2: [50 40 30 20 10]


In [14]:
# Basic Array Operations
print("\nBasic Array Operations:")
print("Addition:", array1 + array2)
print("Subtraction:", array1 - array2)
print("Multiplication:", array1 * array2)
print("Division:", array1 / array2)
print("Floor Division:", array1 // array2)


Basic Array Operations:
Addition: [60 60 60 60 60]
Subtraction: [-40 -20   0  20  40]
Multiplication: [500 800 900 800 500]
Division: [0.2 0.5 1.  2.  5. ]
Division: [0 0 1 2 5]


In [16]:
# Aggregation Functions
print("\nAggregation Functions:")
print("Sum of Array 1:", np.sum(array1))
print("Mean of Array 2:", np.mean(array2))
print("Maximum in Array 1:", np.max(array1))
print("Minimum in Array 2:", np.min(array2))


Aggregation Functions:
Sum of Array 1: 150
Mean of Array 2: 30.0
Maximum in Array 1: 50
Minimum in Array 2: 10


In [17]:
# Trigonometric Functions
print("\nTrigonometric Functions:")
print("Sine of Array 1:", np.sin(array1))
print("Cosine of Array 2:", np.cos(array2))



Trigonometric Functions:
Sine of Array 1: [-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
Cosine of Array 2: [ 0.96496603 -0.66693806  0.15425145  0.40808206 -0.83907153]


In [18]:
# Array Comparison
print("\nArray Comparison:")
print("Greater Than:", array1 > array2)
print("Less Than or Equal To:", array1 <= array2)


Array Comparison:
Greater Than: [False False False  True  True]
Less Than or Equal To: [ True  True  True False False]


In [19]:
# Reshaping Arrays
array3 = np.arange(15).reshape(3, 5)
print("\nReshaped Array:")
print(array3)


Reshaped Array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [20]:
# Transpose
array4 = array3.T
print("\nTransposed Array:")
print(array4)



Transposed Array:
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [21]:

# Matrix Multiplication
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result_matrix = np.dot(matrix1, matrix2)
print("\nMatrix Multiplication Result:")
print(result_matrix)



Matrix Multiplication Result:
[[19 22]
 [43 50]]


In [23]:
# Indexing and Slicing
print("\nIndexing and Slicing:")
print("Element at index 2:", array1[2])
print("First three elements:", array1[:3])
print("Elements at even indices:", array1[::2])




Indexing and Slicing:
Element at index 2: 30
First three elements: [10 20 30]
Elements at even indices: [10 30 50]


In [25]:
# Boolean Indexing
bool_array = array1 > 30
filtered_array = array1[bool_array]
print("\nFiltered Array (Elements > 30):")
print(filtered_array)



Filtered Array (Elements > 3):
[40 50]
